version: '3.7'

services:
    mongo:
        container_name: mongodb
        image: mongo:4.4.3-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - ${MONGODB_PORT}:27017
        volumes:
            - "./mongodb/init:/docker-entrypoint-initdb.d"

    mongo-express:
        container_name: mongo-express
        image: mongo-express:0.54
        ports:
            - ${MONGO_EXPRESS_PORT}:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    
    solr:
        container_name: solr
        build:
            context: ./solr
        ports:
            - ${SOLR_PORT}:8983
        command: -cloud -f